# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deflog.ui'
#
# Created: Tue Dec  2 12:52:42 2008
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 757)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.translateButton = QtGui.QPushButton(self.centralwidget)
        self.translateButton.setGeometry(QtCore.QRect(375, 535, 95, 25))
        self.translateButton.setObjectName("translateButton")
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 806, 496))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originalTextEdit = QtGui.QPlainTextEdit(self.horizontalLayoutWidget)
        self.originalTextEdit.setObjectName("originalTextEdit")
        self.horizontalLayout.addWidget(self.originalTextEdit)
        self.translatedTextEdit = QtGui.QPlainTextEdit(self.horizontalLayoutWidget)
        self.translatedTextEdit.setObjectName("translatedTextEdit")
        self.horizontalLayout.addWidget(self.translatedTextEdit)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 806, 26))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 600, 796, 106))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.desmultiplicar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.desmultiplicar.setChecked(True)
        self.desmultiplicar.setObjectName("desmultiplicar")
        self.gridLayout.addWidget(self.desmultiplicar, 0, 0, 1, 1)
        self.deszezear = QtGui.QCheckBox(self.gridLayoutWidget)
        self.deszezear.setChecked(True)
        self.deszezear.setObjectName("deszezear")
        self.gridLayout.addWidget(self.deszezear, 1, 0, 1, 1)
        self.deskar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.deskar.setChecked(True)
        self.deskar.setObjectName("deskar")
        self.gridLayout.addWidget(self.deskar, 0, 1, 1, 1)
        self.dessmsar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.dessmsar.setChecked(True)
        self.dessmsar.setObjectName("dessmsar")
        self.gridLayout.addWidget(self.dessmsar, 1, 1, 1, 1)
        self.desestupidizar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.desestupidizar.setChecked(True)
        self.desestupidizar.setObjectName("desestupidizar")
        self.gridLayout.addWidget(self.desestupidizar, 0, 2, 1, 1)
        self.desalternar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.desalternar.setChecked(True)
        self.desalternar.setObjectName("desalternar")
        self.gridLayout.addWidget(self.desalternar, 1, 2, 1, 1)
        self.desporteniar = QtGui.QCheckBox(self.gridLayoutWidget)
        self.desporteniar.setChecked(True)
        self.desporteniar.setObjectName("desporteniar")
        self.gridLayout.addWidget(self.desporteniar, 0, 3, 1, 1)
        self.deleet = QtGui.QCheckBox(self.gridLayoutWidget)
        self.deleet.setChecked(True)
        self.deleet.setObjectName("deleet")
        self.gridLayout.addWidget(self.deleet, 1, 3, 1, 1)
        self.fixmissingvowels = QtGui.QCheckBox(self.gridLayoutWidget)
        self.fixmissingvowels.setChecked(True)
        self.fixmissingvowels.setObjectName("fixmissingvowels")
        self.gridLayout.addWidget(self.fixmissingvowels, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(45, 575, 54, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.translateButton, QtCore.SIGNAL("clicked()"), MainWindow.translate)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Traductor de lenguaje flogger a español (desfotologueador)", None, QtGui.QApplication.UnicodeUTF8))
        self.translateButton.setText(QtGui.QApplication.translate("MainWindow", "Traducir", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Texto original:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Texto traducido:", None, QtGui.QApplication.UnicodeUTF8))
        self.desmultiplicar.setText(QtGui.QApplication.translate("MainWindow", "Desmultiplicar", None, QtGui.QApplication.UnicodeUTF8))
        self.deszezear.setText(QtGui.QApplication.translate("MainWindow", "Deszezear", None, QtGui.QApplication.UnicodeUTF8))
        self.deskar.setText(QtGui.QApplication.translate("MainWindow", "Des-k-ar", None, QtGui.QApplication.UnicodeUTF8))
        self.dessmsar.setText(QtGui.QApplication.translate("MainWindow", "desSMSar", None, QtGui.QApplication.UnicodeUTF8))
        self.desestupidizar.setText(QtGui.QApplication.translate("MainWindow", "Desestupidizar", None, QtGui.QApplication.UnicodeUTF8))
        self.desalternar.setText(QtGui.QApplication.translate("MainWindow", "Desalternar", None, QtGui.QApplication.UnicodeUTF8))
        self.desporteniar.setText(QtGui.QApplication.translate("MainWindow", "Desporteñar", None, QtGui.QApplication.UnicodeUTF8))
        self.deleet.setText(QtGui.QApplication.translate("MainWindow", "Deleet", None, QtGui.QApplication.UnicodeUTF8))
        self.fixmissingvowels.setText(QtGui.QApplication.translate("MainWindow", "Fix missing vowels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Métodos", None, QtGui.QApplication.UnicodeUTF8))

